<?php
/**
 * @file
 * A module to show statistics from Google on a specific page for editors
 */
 
/**
 * Implements hook_help.
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */

function epichecker_help($path, $arg) {
	switch ($path) {
		case "admin/help#onpage_statistics" :
			return '<p>' . t("Displays information about a specific URL") . '</p>';
			break;
	}
}

/**
 * Implements hook_block_info().
 */
function onpage_statistics_block_info() {
	$blocks['onpage_statistics'] = array('info' => t('EPiChecker'), //The name that will appear in the block list.
	'cache' => DRUPAL_CACHE_PER_ROLE,   //Default
	);
	return $blocks;
}

function onpage_statistics_block_view($delta = '') {
	switch($delta) {
		case 'epichecker' :
			$block['subject'] = t('EPiChecker');
		
			if (user_access('access content')) {
					
				$block['content'] = epichecker_checkURL();
			}

			break;
	}
	return $block;

}

function epichecker_checkURL() {
	
	//Get domain
	//Add /util/login.aspx
	//Check Header respons
	//IF 404 = not EPiServer
	//IF 301 or 302 redirect, make recursive check for EPiServer
	//Else check below in HTML for login screen /util/login.aspx
	
	//Check if CMS 6
	/*if (checkCMS($content, '/EPiServer CMS 6/')) {
			return array(URL => $url, Version => 'CMS 6');
		}
		//Check if CMS 5
		if (checkCMS($content, '/<h2>/')) {
			return array(URL => $url, Version => 'CMS 5');
		}
		//Check if CMS 4
		if (checkCMS($content, '/table width="100%" height="100%" border="0"/')) {
			return array(URL => $url, Version => 'CMS 4');
	*/
	$content = 'testing';
	
	return $content;
}
